name: Publish

permissions:
    contents: write

on:
    push:
      tags:
        - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Build
      run: echo ${{ github.sha }} > Release.txt
    - name: Test
      run: cat Release.txt
        
    - name: Publish win-x64
      working-directory: src/pg2b3dm      
      run: dotnet publish -c Release -r win-x64 /p:PublishSingleFile=true
    - name: Publish linux-x64
      working-directory: src/pg2b3dm      
      run: dotnet publish -c Release -r linux-x64 /p:PublishSingleFile=true

    - name: Zip win-x64
      run: cd src/pg2b3dm/bin/Release/net6.0/win-x64/publish && zip -r ../../../../../../../pg2b3dm-Win64.zip *
      
    - name: Zip linux-x64
      run: cd src/pg2b3dm/bin/Release/net6.0/linux-x64/publish && zip -r ../../../../../../../pg2b3dm-Linux64.zip *

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          Release.txt
          pg2b3dm-Win64.zip
          pg2b3dm-Linux64.zip
        
    - name: Pack
      working-directory: src/pg2b3dm
      run: |
        dotnet build pg2b3dm.csproj --configuration Release 
        dotnet pack pg2b3dm.csproj --configuration Release -p:PackAsTool=true --output ./nupkg

    - name: Publish to NuGet
      working-directory: src/pg2b3dm
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
      
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Publish to Docker
      run: |
        docker build ./src --file ./src/Dockerfile --tag geodan/pg2b3dm:latest
        docker push geodan/pg2b3dm:latest